# Generated by Django 5.2.3 on 2026-01-07 16:48

import datetime
import django.db.models.deletion
import tutor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(choices=[('', '--Select--'), (1, 'Multiple Choice'), (2, 'True or False'), (3, 'Text Answer from learner'), (4, 'Paragraph Answer from learner ')], default=0, verbose_name='Type of Questions')),
                ('question_number', models.IntegerField(default=1, verbose_name='Question Number')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('mark', models.IntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(default='Quiz 1', max_length=255, unique=True, verbose_name='Quiz Title')),
                ('total_marks', models.IntegerField(default=0)),
                ('duration', models.IntegerField(help_text='Quiz duration in minutes')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, unique=True)),
                ('grade', models.CharField(choices=[('', '----Select----'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=50)),
                ('google_meet_link', models.CharField(blank=True, max_length=200, null=True)),
                ('lesson_time', models.TimeField(blank=True, null=True)),
                ('lesson_days', models.TextField(blank=True, help_text='Enter days of the week separated by commas (e.g., Monday, Wednesday, Friday)', null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ClassLearners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='class_learners', to='tutor.class')),
                ('learner_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_learner_1', to='administration.learner')),
                ('learner_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_learner_2', to='administration.learner')),
                ('learner_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_learner_3', to='administration.learner')),
                ('learner_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_learner_4', to='administration.learner')),
                ('learner_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_learner_5', to='administration.learner')),
            ],
            options={
                'verbose_name': 'Class Learner',
                'verbose_name_plural': 'Class Learners',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutors_full_name', models.CharField(max_length=50)),
                ('parents_full_name', models.CharField(max_length=50)),
                ('learners_full_name', models.CharField(max_length=50)),
                ('month_client_started', models.CharField(choices=[('', '----Select----'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50)),
                ('referrers_name', models.CharField(max_length=50)),
                ('grade_of_learner', models.CharField(choices=[('', '----Select----'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=50)),
                ('subjects_you_tutor', models.TextField()),
                ('number_of_days_you_tutor', models.IntegerField()),
                ('percentage_of_payment_you_are_due', models.CharField(choices=[('', '----Select----'), ('Split Of 70%  Total', 'Split Of 70%  Total'), ('Remainder After Referrer Fee', 'Remainder After Referrer Fee'), ('Slit Of Remainder After Referrer Fee', 'Slit Of Remainder After Referrer Fee')], max_length=50)),
                ('name_of_2nd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('subjects_of_2nd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('name_of_3rd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('subjects_of_3rd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('', '----Select----'), ('Started', 'Started'), ('Start next month/future', 'Start next month/future')], max_length=50)),
                ('date_learner_started_or_due_to_start', models.DateTimeField()),
                ('did_client_pay_this_month', models.CharField(blank=True, choices=[('', '----Select----'), ('YES', 'YES'), ('NO', 'NO')], max_length=50, null=True)),
                ('filled_in_payments_form', models.CharField(blank=True, choices=[('', '----Select----'), ('YES', 'YES'), ('NO', 'NO')], max_length=50, null=True)),
                ('did_you_get_payed_this_month', models.CharField(blank=True, choices=[('', '----Select----'), ('YES', 'YES'), ('NO', 'NO')], max_length=50, null=True)),
                ('amount_client_paid', models.FloatField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.month')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutors_full_name', models.CharField(max_length=50)),
                ('referrers_full_name', models.CharField(max_length=50)),
                ('parents_full_name', models.CharField(max_length=50)),
                ('learners_full_name', models.CharField(max_length=50)),
                ('grade_of_learner', models.CharField(choices=[('', '----Select----'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=50)),
                ('leaners_subjects', models.CharField(max_length=50)),
                ('total_number_of_days_learner_does_per_week', models.IntegerField(blank=True, null=True)),
                ('number_of_days_you_tutor_per_week', models.IntegerField(blank=True, null=True)),
                ('name_of_2nd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('name_of_3rd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_payment', models.DateTimeField()),
                ('proof_of_payment', models.FileField(upload_to=tutor.models.upload_to)),
                ('type_of_subscription', models.CharField(choices=[('', '----Select----'), ('Online Tutoring', 'Online Tutoring'), ('Sporadic Tutoring', 'Sporadic Tutoring'), ('Online Video Lessons', 'Online Video Lessons')], max_length=50)),
                ('cost_of_subscription', models.FloatField()),
                ('month_as_active_client', models.CharField(choices=[('', '----Select----'), ('1st Month', '1st Month'), ('2st Month', '2st Month'), ('3rd Month', '3rd Month'), ('4th Month', '4th Month'), ('5th Month', '5st Month'), ('6th Month', '6th Month'), ('7th Month', '7th Month'), ('8th Month', '8th Month'), ('9th Month', '9th Month'), ('10th Month', '10th Month'), ('11th Month', '11th Month'), ('12th Month', '12th Month')], max_length=50)),
                ('amount_due_to_referrer', models.FloatField()),
                ('amount_due_to_tutor', models.FloatField(blank=True, default=0, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.month')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
                ('is_right', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='tutor.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='tutor.quiz'),
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrers_name', models.CharField(max_length=50)),
                ('parents_full_name', models.CharField(max_length=50)),
                ('learners_full_name', models.CharField(max_length=50)),
                ('month_client_started', models.CharField(choices=[('', '----Select----'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50)),
                ('grade_of_learner', models.CharField(choices=[('', '----Select----'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=50)),
                ('tutors_full_name', models.CharField(max_length=50)),
                ('subjects_tutor_does', models.TextField()),
                ('number_of_days_they_tutor', models.IntegerField()),
                ('percentage_of_payment_you_are_due', models.CharField(choices=[('', '----Select----'), ('20% of Tutors total', '20% of Tutors total'), ('100% of total', '100% of total'), ('Slit Of Remainder After Referrer Fee', 'Slit Of Remainder After Referrer Fee')], max_length=50)),
                ('name_of_2nd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('subjects_of_2nd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('name_of_3rd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('subjects_of_3rd_tutor', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('', '----Select----'), ('Started', 'Started'), ('Start next month/future', 'Start next month/future')], max_length=50)),
                ('date_learner_started_or_due_to_start', models.DateTimeField()),
                ('did_client_pay_this_month', models.CharField(blank=True, choices=[('', '----Select----'), ('YES', 'YES'), ('NO', 'NO')], null=True)),
                ('filled_in_payments_form', models.CharField(blank=True, choices=[('', '----Select----'), ('YES', 'YES'), ('NO', 'NO')], null=True)),
                ('did_you_get_payed_this_month', models.CharField(blank=True, choices=[('', '----Select----'), ('YES', 'YES'), ('NO', 'NO')], null=True)),
                ('amount_client_paid', models.FloatField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.month')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('', '----Select----'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=50)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='tutor.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='tutor.subject'),
        ),
    ]
