# Generated by Django 5.2.3 on 2026-01-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_question_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Quiz Title'),
        ),
    ]
