# Generated by Django 5.2.3 on 2026-01-07 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('tutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='learner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learner',
            name='subject1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject1', to='tutor.subject'),
        ),
        migrations.AddField(
            model_name='learner',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject2', to='tutor.subject'),
        ),
        migrations.AddField(
            model_name='learner',
            name='subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject3', to='tutor.subject'),
        ),
        migrations.AddField(
            model_name='learner',
            name='tutor1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learner',
            name='tutor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learner',
            name='tutor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor3', to=settings.AUTH_USER_MODEL),
        ),
    ]
