# Generated by Django 5.2.3 on 2026-01-07 22:47

import administration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('paper_number', models.PositiveSmallIntegerField(blank=True, choices=[('', '----Select----'), (1, 'Paper 1'), (2, 'Paper 2'), (3, 'Paper 3')], null=True)),
                ('question_file', models.FileField(upload_to=administration.models.past_paper_upload_path)),
                ('memo_file', models.FileField(upload_to=administration.models.past_paper_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='tutor.subject')),
            ],
        ),
    ]
